language: csharp
dotnet: 2.2
sudo: required
dist: xenial
solution: ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
install:
  - nuget restore ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
node_js:
  - 8
cache:
  directories:
    - SourceCodes/FiscalPrinterSimulatorClient/node_modules
script:
  - cd SourceCodes/FiscalPrinterSimulatorClient/
  - npm install
  - npm run build
  - npm run test:cov
  - npm run electron-pack-x64
  - cd ../../
  - dotnet build ./SourceCodes/FiscalPrinterSimulatorService --configuration Release --verbosity n /p:Platform=x64
  - dotnet test ./SourceCodes/FiscalPrinterSimulatorService
  - cd ./CI/WixInstaller/FiscalPrinterSimulatorInstaller
  - ../packages/WiX.3.11.1/tools/candle.exe -dPlatform=x64 -dVersion=0.0.1 Product.wxs -out myinstaller.wixobj
  - ../packages/WiX.3.11.1/tools/light.exe myinstaller.wixobj -cultures:en-us -loc Translations/EnglishLanguage.wxl -out test-installer-en.msi -ext ../packages/WiX.3.11.1/tools/WixUIExtension
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: test-installer-en.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
