os: windows
language: csharp
mono: none
sudo: required
dist: xenial
install:
  - Powershell -Command dotnet-install.ps1
  - Invoke-WebRequest "https://download.microsoft.com/download/9/B/B/9BB1309E-1A8F-4A47-A6C5-ECF76672A3B3/BuildTools_Full.exe" -OutFile "BuildTools_Full.exe"
  - BuildTools_Full.exe /Silent /Full
  - Install-WindowsFeature NET-Framework-47
node_js:
  - 8
cache:
  directories:
    - SourceCodes/FiscalPrinterSimulatorClient/node_modules
script:
  - cd SourceCodes/FiscalPrinterSimulatorClient/
  - npm install
  - npm run build
  - npm run test:cov
  - cd ../../
  - dotnet restore ./SourceCodes/FiscalPrinterSimulatorService
  - dotnet build ./SourceCodes/FiscalPrinterSimulatorService --configuration Release --verbosity n /p:Platform=x64
  - dotnet test ./SourceCodes/FiscalPrinterSimulatorService
  - MSBuild ./CI/FiscalPrinterSimulatorInstaller.sln
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: Delivery/SetupFiscalPrinterSimulatorx64-en_US.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true



















