language: csharp
#dotnet: 2.2
sudo: required
#services: docker
dist: xenial
solution: ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
install:
  - nuget restore ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
script:
  - BASE_DIR=/home/travis/build/fiscal-printer-simulator/Fiscal-Printer-Simulator-Setup-Builder
  - PACKAGES_DIR=$BASE_DIR/CI/WixInstaller/packages/WiX.3.11.1/tools
  - WIX_PROJ_DIR=$BASE_DIR/CI/WixInstaller/FiscalPrinterSimulatorInstaller
  - DELIVERY_DIR=$BASE_DIR/delivery
  - RESOURCES_DIR=$BASE_DIR/Resources
  - TRANSLATIONS_DIR=$RESOURCES_DIR/Translations
  - LICENCE_PATH=$RESOURCES_DIR/Licences
  - ls $PACKAGES_DIR
  - |
    $PACKAGES_DIR/candle.exe     -dVersion=0.0.2 \
    -dConfiguration=Release \
    -dPlatform=x64 \
    -dTargetDir=$DELIVERY_DIR \
    -dTargetExt=.msi \
    -dTargetFileName=SetupFiscalPrinterSimulatorx64.msi \
    -dTargetName=SetupFiscalPrinterSimulatorx64 \
    -dResourcesDir=$RESOURCES_DIR \
    -dLicencePath=$LICENCE_PATH/Licence-en.rtf \
    -dTargetPath=$DELIVERY_DIR/SetupFiscalPrinterSimulatorx64.msi  \
    -arch x64 \
    -out myinstaller.wixobj
    $WIX_PROJ_DIR/Product.wxs
  - mkdir $DELIVERY_DIR -p 
  - ls
  - ls delivery 
  - ls CI
  - ls $WIX_PROJ_DIR
  - |
    $PACKAGES_DIR/light.exe \
    -out delivery/SetupFiscalPrinterSimulatorx64.msi \
    -pdbout delivery/SetupFiscalPrinterSimulatorx64.wixpdb \
    -cultures:en-US \
    -loc CI/WixInstaller/FiscalPrinterSimulatorInstaller/Translations/EnglishLanguage.wxl \
    myinstaller.wixobj
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: test-installer-en.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
