--- 
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: Delivery/SetupFiscalPrinterSimulatorx64-en_US.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
dist: xenial
dotnet: 2.2
language: node_js
mono: none
os: windows
script: 
  - "CI\\CakeScripts\\build.ps1 -Configuration=Release -TargetPlatform=x64"
sudo: required
