before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: Delivery/SetupFiscalPrinterSimulatorx64-en_US.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
dist: xenial
dotnet: 2.2
language: node_js
mono: none
os: windows
node_js:
  - 8
install:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
script: 
  - Powershell -Command CI\CakeScripts\build.ps1 -Configuration=Release -TargetPlatform=x64
sudo: required
