language: csharp
dotnet: 2.2
sudo: required
dist: xenial
solution: ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
install:
  # - sudo apt install nuget
  # - dotnet restore ./SourceCodes/FiscalPrinterSimulatorService
  - nuget restore ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
node_js:
  - 8
cache:
  directories:
    - SourceCodes/FiscalPrinterSimulatorClient/node_modules
script:
  - cd SourceCodes/FiscalPrinterSimulatorClient/
  - npm install
  - npm run build
  - npm run test:cov
  - cd ../../
  - dotnet build ./SourceCodes/FiscalPrinterSimulatorService --configuration Release --verbosity n /p:Platform=x64
  - dotnet test ./SourceCodes/FiscalPrinterSimulatorService
  #- nuget restore ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
  - cd ./CI/WixInstaller/FiscalPrinterSimulatorInstaller
  - ls
  - ls ../
  - ls ../../
  - ls ../../../
  - ls ../../../Resources
  - ls ../../../Resources/Binaries
  - ../packages/WiX.3.11.1/tools/candle.exe -dPlatform=x64 -dVersion=0.0.1 Product.wxs -out myinstaller.wixobj
  - ../packages/WiX.3.11.1/tools/light.exe myinstaller.wixobj -cultures:en-us -loc Translations/EnglishLanguage.wxl -out myInstaller-en-us.msi -ext ../packages/WiX.3.11.1/tools/WixUIExtension
  #- mv ./CI/WixInstaller/packages/WiX.3.11.1/tools/light.exe ./CI/WixInstaller/packages/WiX.3.11.1/tools/Light.exe
  #- ls ./CI/WixInstaller/packages/WiX.3.11.1/tools
  #- msbuild ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: Delivery/SetupFiscalPrinterSimulatorx64-en_US.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
