os: windows
language: csharp
mono: none
dotnet: 2.2
sudo: required
dist: xenial
install:
  - Install-WindowsFeature NET-Framework-47
node_js:
  - 8
cache:
  directories:
    - SourceCodes/FiscalPrinterSimulatorClient/node_modules
script:
  - cd SourceCodes/FiscalPrinterSimulatorClient/
  - npm install
  - npm run build
  - npm run test:cov
  - cd ../../
  - dotnet restore ./SourceCodes/FiscalPrinterSimulatorService
  - dotnet build ./SourceCodes/FiscalPrinterSimulatorService --configuration Release --verbosity n /p:Platform=x64
  - dotnet test ./SourceCodes/FiscalPrinterSimulatorService
  - msbuild ./CI/FiscalPrinterSimulatorInstaller.sln
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: Delivery/SetupFiscalPrinterSimulatorx64-en_US.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
