language: csharp
#dotnet: 2.2
sudo: required
#services: docker
dist: xenial
solution: ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
install:
  - nuget restore ./CI/WixInstaller/FiscalPrinterSimulatorInstaller.sln
script:
  - BASE_DIR=/home/travis/build/fiscal-printer-simulator/Fiscal-Printer-Simulator-Setup-Builder
  - PACKAGES_DIR=$BASE_DIR/CI/WixInstaller/packages/WiX.3.11.1/tools
  - WIX_PROJ_DIR=$BASE_DIR/CI/WixInstaller/FiscalPrinterSimulatorInstaller
  - DELIVERY_DIR=$BASE_DIR/delivery
  - RESOURCES_DIR=$BASE_DIR/Resources
  - TRANSLATIONS_DIR=$RESOURCES_DIR/Translations
  - LICENCE_PATH=$RESOURCES_DIR/Licences
  - ls $PACKAGES_DIR
  - $PACKAGES_DIR/candle.exe   -dVersion=0.0.2 -dConfiguration=Release -dPlatform=x64 -dTargetDir=$DELIVERY_DIR -dTargetExt=.msi -dTargetFileName=SetupFiscalPrinterSimulatorx64.msi -dTargetName=SetupFiscalPrinterSimulatorx64 -dResourcesDir=$RESOURCES_DIR -dLicencePath=$LICENCE_PATH/Licence-en.rtf -dTargetPath=$DELIVERY_DIR/SetupFiscalPrinterSimulatorx64.msi  -arch x64 -out myinstaller.wixobj $WIX_PROJ_DIR/Product.wxs
  - mkdir $DELIVERY_DIR -p 
  - ls
  - ls delivery 
  - ls CI
  - ls $WIX_PROJ_DIR
  - $PACKAGES_DIR/light.exe -out delivery/SetupFiscalPrinterSimulatorx64.msi -pdbout delivery/SetupFiscalPrinterSimulatorx64.wixpdb -cultures:en-US -loc CI/WixInstaller/FiscalPrinterSimulatorInstaller/Translations/EnglishLanguage.wxl myinstaller.wixobj 
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_deploy: 
  - "git config --local user.name \"wojcikmm\""
  - "git config --local user.email \"m.mwojcik@outlook.com\""
deploy: 
  api_key: GITHUB_TOKEN
  draft: true
  file: test-installer-en.msi
  provider: releases
  skip_cleanup: true
  true: 
    tags: true


$ ../packages/WiX.3.11.1/tools/candle.exe -dPlatform=x64 -dVersion=0.0.1 Product.wxs -out myinstaller.wixobj
Windows Installer XML Toolset Compiler version 
Copyright (c) .NET Foundation and contributors. All rights reserved.
Product.wxs
The command "../packages/WiX.3.11.1/tools/candle.exe -dPlatform=x64 -dVersion=0.0.1 Product.wxs -out myinstaller.wixobj" exited with 0.


-----------------------------------------------
$ ../packages/WiX.3.11.1/tools/light.exe myinstaller.wixobj -cultures:en-us -loc Translations/EnglishLanguage.wxl -out test-installer-en.msi -ext ../packages/WiX.3.11.1/tools/WixUIExtension
Windows Installer XML Toolset Linker version 
Copyright (c) .NET Foundation and contributors. All rights reserved.
light.exe : error LGHT0001 : Invalid Image
Exception Type: System.IO.FileNotFoundException
Stack Trace:
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFile_internal(string,System.Threading.StackCrawlMark&)
  at System.Reflection.Assembly.LoadFile (System.String path, System.Security.Policy.Evidence securityEvidence) [0x0002d] in <15c986724bdc480293909469513cfdb3>:0 
  at System.Reflection.Assembly.LoadFile (System.String path) [0x00000] in <15c986724bdc480293909469513cfdb3>:0 
  at Microsoft.Tools.WindowsInstallerXml.Binder.ExtractCabinets (System.Collections.Hashtable cabinets) [0x00068] in <df790cde4823466b88b6fb893e19a9be>:0 
  at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase (Microsoft.Tools.WindowsInstallerXml.Output output, System.String databaseFile) [0x00620] in <df790cde4823466b88b6fb893e19a9be>:0 
  at Microsoft.Tools.WindowsInstallerXml.Binder.Bind (Microsoft.Tools.WindowsInstallerXml.Output output, System.String file) [0x00298] in <df790cde4823466b88b6fb893e19a9be>:0 
  at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run (System.String[] args) [0x009b1] in <794f56962d5b40c4aa09607a485d0347>:0 
The command "../packages/WiX.3.11.1/tools/light.exe myinstaller.wixobj -cultures:en-us -loc Translations/EnglishLanguage.wxl -out test-installer-en.msi -ext ../packages/WiX.3.11.1/tools/WixUIExtension" exited with 1.
