matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - cd ./SourceCodes/FiscalPrinterSimulatorClient
  - docker run -ti --rm -v $FP_SIMULATOR_CLIENT_RESOURCE_DIR:/Resources/Binaries/Client -v $FP_SIMULATOR_CLIENT_DIR:/app electronuserland/builder:wine bash -c "cd /app && npm install && npm run electron-pack-x64-win"
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"